### ISSUE TITLE
The RUT is not saved with dots and dash in the database

### ISSUE THREAD

**Issue by MSaez** [sateler/yii2-rut#2]
Is there any way to configure it so that when I save the rut I keep the points and the dash? Since when it saves the record it appears without them.

Thank you for your excellent work in this extension.

**Comment by fsateler** [comment]
Not currently, no. Patches welcome for adding a configuration option. The option should be checked here:

https://github.com/sateler/yii2-rut/blob/master/RutValidator.php#L67

**Comment by MSaez** [comment]
Oh I see...

Thanks for you answer :)
